# Generated by Django 2.2.24 on 2022-06-30 16:49

from django.db import migrations


def fill_new_building_field(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()
    for flat in flats.iterator():
        if flat.construction_year:
            flat.new_building = flat.construction_year >= 2015
            flat.save()
        else:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('property', 'fill_new_building_field'),
    ]

    operations = [
        migrations.RunPython(fill_new_building_field)
    ]
