# Generated by Django 2.2.24 on 2022-06-30 20:13
import phonenumbers

from django.db import migrations


def fill_pure_phonenumber(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()
    for flat in flats.iterator():
        phone_number = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number_for_region(phone_number, 'RU'):
            flat.owner_pure_phone = f'+{phone_number.country_code}{phone_number.national_number}'
        else:
            flat.owner_pure_phone = ''
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(fill_pure_phonenumber)
    ]
