# Generated by Django 2.2.24 on 2022-06-30 20:59

from django.db import migrations


def transfer_phonenumbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flats = Flat.objects.all()
    for flat in flats.iterator():
        Owner.objects.get_or_create(
            full_name=flat.owner,
            phonenumber=flat.owners_phonenumber,
            pure_phonenumber=flat.owner_pure_phone
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20220630_2354'),
    ]

    operations = [
        migrations.RunPython(transfer_phonenumbers)
    ]
