# Generated by Django 2.2.24 on 2022-06-30 14:52
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_flat_new_building'),
    ]

    def fill_new_building_field(apps, schema_editor):
        Flat = apps.get_model('property', 'Flat')
        flats = Flat.objects.all()
        for flat in flats.iterator():
                flat.new_building = flat.construction_year >= 2015

    operations = [
        migrations.RunPython(fill_new_building_field)
    ]
